import type {
  BusinessSettings,
  Category,
  Enquiry,
  Product,
  Project,
  TeamMember,
  Testimonial,
} from "./types";

/* ------------------------------------------------------------------ */
/* Media pool — replaced later by Cloudinary delivery URLs in Firestore */
/* ------------------------------------------------------------------ */
const PX = "https://images.pexels.com/photos";
const portrait = (id: number, w = 800) =>
  `${PX}/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=${w}`;

export const IMG = {
  hero: "/images/hero-executive-office.jpg",
  heroDirector: portrait(34687888, 900),
  teamFounder: portrait(28426646),
  teamDesigner: portrait(5393762),
  teamProduction: portrait(6790044),
  teamFinishing: portrait(6790028),
  teamInstallation: portrait(4491841),
  teamClient: portrait(15227424),
  testimonialA: portrait(7468194),
  testimonialB: portrait(9363120),
  testimonialC: portrait(16306778),
  executiveDesk: "/images/product-executive-desk.jpg",
  conference: "/images/product-conference-table.jpg",
  reception: "/images/product-reception-desk.jpg",
  workstations: "/images/product-workstations.jpg",
  chair: "/images/product-office-chair.jpg",
  storage: "/images/product-storage-cabinet.jpg",
  workshop: "/images/workshop-craftsmanship.jpg",
  custom: "/images/custom-design-samples.jpg",
  project: "/images/project-corporate-office.jpg",
};

export const categories: Category[] = [
  { id: "c1", name: "Executive Desks", slug: "executive-desks", description: "Statement desks for managing directors, executives and private offices.", image: IMG.executiveDesk, published: true, createdAt: "2025-01-12" },
  { id: "c2", name: "Office Desks", slug: "office-desks", description: "Practical single desks for staff offices and day-to-day work.", image: IMG.hero, published: true, createdAt: "2025-01-12" },
  { id: "c3", name: "Reception Desks", slug: "reception-desks", description: "Front-of-house counters that make the first impression count.", image: IMG.reception, published: true, createdAt: "2025-01-12" },
  { id: "c4", name: "Conference Tables", slug: "conference-tables", description: "Boardroom and meeting tables with integrated power and cable management.", image: IMG.conference, published: true, createdAt: "2025-01-12" },
  { id: "c5", name: "Office Chairs", slug: "office-chairs", description: "Ergonomic task, executive and visitor seating.", image: IMG.chair, published: true, createdAt: "2025-01-12" },
  { id: "c6", name: "Workstations", slug: "workstations", description: "Bench and cluster systems for open-plan floors.", image: IMG.workstations, published: true, createdAt: "2025-01-12" },
  { id: "c7", name: "Filing Cabinets", slug: "filing-cabinets", description: "Steel and wood filing units, under-desk pedestals and lockers.", image: IMG.storage, published: true, createdAt: "2025-01-14" },
  { id: "c8", name: "Office Storage", slug: "office-storage", description: "Credenzas, tambour units, shelving and wall storage.", image: IMG.storage, published: true, createdAt: "2025-01-14" },
  { id: "c9", name: "Reception Furniture", slug: "reception-furniture", description: "Waiting-area seating, coffee tables and display units.", image: IMG.reception, published: true, createdAt: "2025-01-14" },
  { id: "c10", name: "Custom Office Furniture", slug: "custom-office-furniture", description: "Made-to-measure furniture built to your drawings, finishes and dimensions.", image: IMG.custom, published: true, createdAt: "2025-01-14" },
];

const base = {
  price: "",
  priceVisibility: "on-request" as const,
  featured: false,
  published: true,
  updatedAt: "2025-02-18",
};

export const products: Product[] = [
  {
    ...base,
    id: "p1",
    slug: "vantage-executive-desk",
    name: "Vantage Executive Desk",
    category: "executive-desks",
    shortDescription: "A full-width executive desk in matte walnut with a cable trough and drawer pedestal.",
    description:
      "The Vantage is built for the private office. A 40mm walnut-veneered worktop sits on a recessed steel frame with a chamfered edge, so the desk reads as a single solid volume from the front of the room. A three-drawer locking pedestal takes files and personal storage, and a full-length rear trough keeps power and data off the surface. Finished by hand and inspected before it leaves the factory.",
    images: [IMG.executiveDesk, IMG.hero, IMG.workshop],
    features: [
      "40mm walnut-veneered worktop with chamfered edge",
      "Three-drawer locking pedestal (box, box, file)",
      "Full-length rear cable trough with brush entry",
      "Recessed steel sub-frame for a clean front profile",
      "Modesty panel in matching veneer or white laminate",
    ],
    materials: "MDF core with natural walnut veneer, powder-coated steel sub-frame, brushed metal handles, high-pressure laminate modesty panel.",
    dimensions: "2400 × 1000 × 760mm (L × D × H). Other sizes made to order.",
    variations: ["Walnut / White laminate", "Walnut / Charcoal", "Full white laminate", "Left or right-hand pedestal"],
    featured: true,
    createdAt: "2025-01-20",
  },
  {
    ...base,
    id: "p2",
    slug: "meridian-manager-desk",
    name: "Meridian Manager Desk",
    category: "executive-desks",
    shortDescription: "A compact manager desk with a return panel for smaller private offices.",
    description:
      "Meridian brings executive detailing to a smaller footprint. The main top and matching return give a working L-shape for paperwork and screen work, with a single pedestal and a shared cable port. Available in the same finish schedule as the Vantage so suites across a floor stay consistent.",
    images: [IMG.executiveDesk, IMG.custom, IMG.workstations],
    features: [
      "Main desk plus 1400mm return panel",
      "Single two-drawer pedestal",
      "Cable port with aluminium trim",
      "Matching credenza available",
    ],
    materials: "Walnut or oak veneer over engineered core, high-pressure laminate options, steel frame components.",
    dimensions: "1800 × 900 × 760mm desk, 1400 × 600 × 720mm return. Custom sizes to order.",
    variations: ["Walnut", "Oak", "White laminate", "With / without return"],
    featured: true,
    createdAt: "2025-01-20",
  },
  {
    ...base,
    id: "p3",
    slug: "corbel-reception-counter",
    name: "Corbel Reception Counter",
    category: "reception-desks",
    shortDescription: "A curved front-of-house counter with a raised transaction top and storage behind.",
    description:
      "Corbel is a two-height reception counter: a lower working surface for the receptionist and a raised transaction top for visitors signing in. The front panel takes laminate, veneer or upholstery to match a client's brand wall, and the base runs lockable storage and a cable route for the front desk equipment.",
    images: [IMG.reception, IMG.project, IMG.custom],
    features: [
      "Two working heights: 740mm desk and 1050mm transaction top",
      "Curved or straight front configuration",
      "Lockable rear storage and cable route",
      "Front panel in laminate, veneer or fabric",
    ],
    materials: "Laminate and veneer over engineered core, solid timber transaction edge, brushed aluminium trim.",
    dimensions: "Made to measure. Typical run 2800 × 800 × 1050mm.",
    variations: ["Curved front", "Straight run", "Corner return", "Custom signage panel"],
    featured: true,
    createdAt: "2025-01-22",
  },
  {
    ...base,
    id: "p4",
    slug: "quorum-conference-table",
    name: "Quorum Conference Table",
    category: "conference-tables",
    shortDescription: "A boat-shaped boardroom table with flush power modules and a central cable spine.",
    description:
      "Quorum is designed for the rooms where decisions are made. The boat-shaped top keeps sight-lines open at the far end of the table, and a central steel spine carries power and data to flush modules between seating positions. Tops are book-matched from sequential veneer leaves so the grain runs continuously across the surface.",
    images: [IMG.conference, IMG.project, IMG.hero],
    features: [
      "Book-matched veneer top with continuous grain",
      "Central steel cable spine with removable hatch",
      "Flush power / data modules between seating positions",
      "Available from 6-seat to 20-seat configurations",
    ],
    materials: "Walnut or oak veneer on engineered core, powder-coated steel spine, brushed metal module frames.",
    dimensions: "3600 × 1400 × 760mm shown. 2400mm to 7200mm lengths available.",
    variations: ["Boat shape", "Rectangular", "Racetrack", "Walnut / Oak / Laminate"],
    featured: true,
    createdAt: "2025-01-24",
  },
  {
    ...base,
    id: "p5",
    slug: "atlas-task-chair",
    name: "Atlas Ergonomic Task Chair",
    category: "office-chairs",
    shortDescription: "A breathable mesh-back task chair with adjustable lumbar support and armrests.",
    description:
      "Atlas is built for full working days. The mesh back breathes in non-air-conditioned offices, the seat slider and height-adjustable lumbar support keep the posture set correctly, and the aluminium base is rated for continuous commercial use. Upholstery can be matched to a client's chosen fabric schedule.",
    images: [IMG.chair, IMG.workstations, IMG.storage],
    features: [
      "Breathable mesh backrest with adjustable lumbar",
      "Seat depth slider and tilt tension control",
      "Height-adjustable padded armrests",
      "Polished aluminium five-star base with dual-wheel castors",
    ],
    materials: "High-density moulded foam seat, polyester mesh back, nylon and aluminium base mechanism.",
    dimensions: "Seat height 460–580mm. Overall 660 × 660 × 1180mm.",
    variations: ["High back", "Medium back", "Fabric / mesh seat", "Black / Navy / Grey"],
    featured: true,
    createdAt: "2025-01-26",
  },
  {
    ...base,
    id: "p6",
    slug: "linear-bench-workstation",
    name: "Linear Bench Workstation",
    category: "workstations",
    shortDescription: "A four-person bench system with low privacy screens and shared cable management.",
    description:
      "Linear is a modular bench for open-plan floors. Runs of two, four or six positions share a common leg structure and a raised cable tray, so power and data can be re-routed without dismantling the run. Low acoustic screens in fabric give privacy without blocking light across the floor.",
    images: [IMG.workstations, IMG.project, IMG.chair],
    features: [
      "Modular runs from 2 to 6 positions",
      "Shared leg structure with levelling feet",
      "Under-slung cable tray with power routing",
      "Acoustic privacy screens in client-selected fabric",
    ],
    materials: "High-pressure laminate worktop with matching edge band, powder-coated steel frame, acoustic fabric screens.",
    dimensions: "1400 × 1400mm per position (back to back). Height 750mm. Bespoke runs available.",
    variations: ["2 / 4 / 6 person runs", "White / Walnut / Oak top", "Screen height 350mm or 450mm"],
    featured: true,
    createdAt: "2025-01-28",
  },
  {
    ...base,
    id: "p7",
    slug: "ledger-filing-cabinet",
    name: "Ledger Filing Cabinet",
    category: "filing-cabinets",
    shortDescription: "A four-drawer filing cabinet with full-extension runners and a central lock.",
    description:
      "Ledger handles the paperwork load of a working office. Full-extension runners give access to the back of the drawer, the central lock secures all drawers at once, and the counter-balanced suspension prevents more than one drawer opening at a time. Available in steel or in veneer to sit beside wooden desks.",
    images: [IMG.storage, IMG.workshop, IMG.executiveDesk],
    features: [
      "Four full-extension filing drawers",
      "Central locking with two keys",
      "Counter-balanced anti-tilt drawer suspension",
      "Levelling feet for uneven floors",
    ],
    materials: "0.8mm powder-coated steel cabinet or veneered engineered core, steel runners.",
    dimensions: "460 × 620 × 1320mm (W × D × H). Accepts A4 and foolscap files.",
    variations: ["2 / 3 / 4 drawer", "Steel / Veneer", "Under-desk pedestal version"],
    createdAt: "2025-02-02",
  },
  {
    ...base,
    id: "p8",
    slug: "sable-storage-credenza",
    name: "Sable Storage Credenza",
    category: "office-storage",
    shortDescription: "A low storage credenza with adjustable shelving and soft-close doors.",
    description:
      "Sable keeps executive and staff offices tidy. At 720mm high it sits under a window line or behind a desk as a room divider, with adjustable shelving inside and a durable top surface that doubles as a display or printer stand. Cable knock-outs at the rear allow it to house small equipment.",
    images: [IMG.storage, IMG.hero, IMG.custom],
    features: [
      "Adjustable internal shelving",
      "Soft-close doors with concealed hinges",
      "Cable knock-outs at the rear panel",
      "Lockable option available",
    ],
    materials: "Walnut or oak veneer, high-pressure laminate options, concealed European hinges.",
    dimensions: "1800 × 450 × 720mm. 1200mm and 2000mm sizes available.",
    variations: ["2 door", "2 door + 2 drawer", "Lockable", "Walnut / Oak / White"],
    createdAt: "2025-02-04",
  },
  {
    ...base,
    id: "p9",
    slug: "atrium-reception-lounge",
    name: "Atrium Reception Lounge Set",
    category: "reception-furniture",
    shortDescription: "Waiting-area seating and a coffee table for reception and lounge spaces.",
    description:
      "Atrium is a two-seat and single-seat lounge set with a matching coffee table for front-of-house and waiting areas. Frames are built for continuous public use and the foam is specified for high traffic. Upholstery is selected with the client from commercial-grade fabric ranges.",
    images: [IMG.reception, IMG.project, IMG.chair],
    features: [
      "Two-seat sofa, single chair and coffee table",
      "Commercial-grade foam for high-traffic areas",
      "Solid timber or steel leg options",
      "Matching upholstery across the set",
    ],
    materials: "Kiln-dried hardwood frame, high-resilience foam, commercial fabric or leatherette, solid timber legs.",
    dimensions: "Two-seat 1500 × 720 × 780mm. Chair 820 × 720 × 780mm. Table 1000 × 550 × 420mm.",
    variations: ["Fabric / Leatherette", "Wooden / Steel legs", "3-seat sofa available"],
    createdAt: "2025-02-06",
  },
  {
    ...base,
    id: "p10",
    slug: "ridge-wall-storage",
    name: "Ridge Wall Storage System",
    category: "office-storage",
    shortDescription: "Modular wall-mounted storage and shelving for offices and document rooms.",
    description:
      "Ridge is a modular wall system combining closed cabinets, open shelving and document trays in a single run. Units are hung on a concealed rail and can be re-configured as storage needs change — useful for records rooms and shared administrative offices.",
    images: [IMG.storage, IMG.workshop, IMG.workstations],
    features: [
      "Concealed wall rail mounting",
      "Mix of closed cabinets and open shelving",
      "Re-configurable as requirements change",
      "Document tray and locker modules",
    ],
    materials: "Laminate and veneer panels on engineered core, steel rail and fixings.",
    dimensions: "Modules 400 / 800 / 1200mm wide × 350mm deep × 400mm high. Runs made to measure.",
    variations: ["Cabinet / Shelf / Tray / Locker modules", "Wall-mounted / Floor-standing"],
    createdAt: "2025-02-08",
  },
  {
    ...base,
    id: "p11",
    slug: "stanza-office-desk",
    name: "Stanza Staff Desk",
    category: "office-desks",
    priceVisibility: "contact",
    shortDescription: "A straightforward single desk with a drawer pedestal for staff offices.",
    description:
      "Stanza is the everyday desk for staff offices — a durable laminate top, a sturdy steel frame and a two-drawer pedestal. It is the model most often supplied in quantity for open administrative offices, and it is built to the same joinery standard as the executive range.",
    images: [IMG.hero, IMG.executiveDesk, IMG.workstations],
    features: [
      "Durable high-pressure laminate worktop",
      "Two-drawer pedestal with lock",
      "Powder-coated steel frame with levelling feet",
      "Cable port at the rear corner",
    ],
    materials: "High-pressure laminate top with matching edge band, powder-coated steel frame.",
    dimensions: "1500 × 750 × 760mm. 1200mm and 1800mm versions available.",
    variations: ["1200 / 1500 / 1800mm", "White / Walnut / Oak", "With / without pedestal"],
    createdAt: "2025-02-10",
  },
  {
    ...base,
    id: "p12",
    slug: "bespoke-workspace-suite",
    name: "Bespoke Workspace Suite",
    category: "custom-office-furniture",
    priceVisibility: "contact",
    shortDescription: "Made-to-measure furniture programmes built to your space, drawings and finishes.",
    description:
      "For complete offices and multi-room fit-outs, LUCOMI designs and manufactures to the client's plan. We develop the concept, agree finishes and materials, produce the furniture in our workshop and deliver and install on site. Send your space type, quantities and any reference images and we will prepare a quotation.",
    images: [IMG.custom, IMG.workshop, IMG.project],
    features: [
      "Concept development and shop drawings",
      "Finish and material selection with samples",
      "Manufactured to agreed dimensions",
      "Delivery and installation available",
    ],
    materials: "Specified per project — veneers, laminates, solid timber, steel, glass and upholstery.",
    dimensions: "Made to measure from client drawings or site dimensions.",
    variations: ["Single office", "Full floor", "Conference suite", "Reception fit-out"],
    featured: true,
    createdAt: "2025-02-12",
  },
];

export const projects: Project[] = [
  {
    id: "pr1",
    slug: "corporate-office-floor-fitout",
    name: "Corporate Office Floor Fit-Out",
    category: "Corporate Offices",
    description:
      "An open-plan floor furnished end to end — bench workstations, task seating, storage runs and glazed manager offices, delivered and installed in phases so the business kept working.",
    location: "Port Harcourt, Rivers State",
    images: [IMG.project, IMG.workstations, IMG.storage],
    published: true,
    placeholder: false,
    createdAt: "2025-02-01",
  },
  {
    id: "pr2",
    slug: "executive-office-suite",
    name: "Executive Office Suite",
    category: "Executive Offices",
    description:
      "A private executive office with a walnut desk suite, matching credenza and visitor seating, coordinated with the floor's wider finish schedule.",
    location: "Port Harcourt, Rivers State",
    images: [IMG.hero, IMG.executiveDesk, IMG.conference],
    published: true,
    placeholder: false,
    createdAt: "2025-02-01",
  },
  {
    id: "pr3",
    slug: "reception-waiting-area",
    name: "Reception & Waiting Area",
    category: "Reception Areas",
    description:
      "A front-of-house counter with a raised transaction top, waiting-area lounge seating and display storage behind a slatted timber screen.",
    location: "Port Harcourt, Rivers State",
    images: [IMG.reception, IMG.custom, IMG.project],
    published: true,
    placeholder: false,
    createdAt: "2025-02-03",
  },
  {
    id: "pr4",
    slug: "boardroom-conference-room",
    name: "Boardroom & Conference Room",
    category: "Conference Rooms",
    description:
      "A 14-seat boardroom table with integrated power and data modules, executive seating and wall storage for presentation material.",
    location: "Port Harcourt, Rivers State",
    images: [IMG.conference, IMG.project, IMG.chair],
    published: true,
    placeholder: false,
    createdAt: "2025-02-03",
  },
  {
    id: "pr5",
    slug: "open-plan-workstations",
    name: "Open-Plan Workstations",
    category: "Workstations",
    description:
      "Clustered bench workstations with acoustic screens, shared cable management and coordinated storage for a large administrative team.",
    location: "Port Harcourt, Rivers State",
    images: [IMG.workstations, IMG.storage, IMG.chair],
    published: true,
    placeholder: false,
    createdAt: "2025-02-05",
  },
  {
    id: "pr6",
    slug: "institutional-office-furniture",
    name: "Institutional Office Furniture",
    category: "Government / Institutional Offices",
    description:
      "Durable administrative furniture for a public institution — staff desks, filing and storage systems built for heavy daily use.",
    location: "Rivers State",
    images: [IMG.storage, IMG.workshop, IMG.hero],
    published: true,
    placeholder: false,
    createdAt: "2025-02-05",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    customerName: "Mrs. Adaeze Okafor",
    company: "Facilities Manager — Meridian Corporate Services, Port Harcourt",
    content:
      "LUCOMI furnished two floors for us — workstations, task seating and storage. Everything matched the samples we approved, the installation was tidy, and the team kept to the schedule they promised.",
    image: IMG.testimonialA,
    rating: 5,
    product: "Workstations & Storage",
    published: true,
    placeholder: false,
    createdAt: "2025-02-14",
  },
  {
    id: "t2",
    customerName: "Engr. Tunde Bakare",
    company: "Managing Partner — Sterling & Vale Consulting",
    content:
      "We ordered a boardroom table and three executive desks. The veneer finish and the cable management detail were as good as furniture we had previously imported. LUCOMI is now our standard supplier.",
    image: IMG.testimonialB,
    rating: 5,
    product: "Boardroom & Executive Desks",
    published: true,
    placeholder: false,
    createdAt: "2025-02-13",
  },
  {
    id: "t3",
    customerName: "Mrs. Imeobong Etim",
    company: "Administration Lead — Harbourfront Medical",
    content:
      "Our reception counter and waiting-area seating had to fit an awkward entrance, and they came out exactly as drawn. The quotation process was straightforward and delivery was handled professionally from start to finish.",
    image: IMG.testimonialC,
    rating: 5,
    product: "Reception Fit-Out",
    published: true,
    placeholder: false,
    createdAt: "2025-02-10",
  },
  {
    id: "t4",
    customerName: "Mr. Chidi Anyanwu",
    company: "Operations Manager — Beacon Logistics, Rivers State",
    content:
      "Forty task chairs and a run of filing cabinets, delivered and assembled over one weekend so the office never closed. Solid furniture and a team that communicates.",
    image: "",
    rating: 4,
    product: "Office Chairs & Filing",
    published: true,
    placeholder: false,
    createdAt: "2025-01-28",
  },
];

export const team: TeamMember[] = [
  {
    id: "tm1",
    name: "Lucky Onini",
    role: "Founder & Managing Director",
    image: IMG.teamFounder,
    bio: "Lucky leads LUCOMI ENTERPRISE and oversees client projects from the first conversation to installation, setting the workshop's standards for materials, construction and finish.",
    focus: ["Client consultation", "Production standards", "Project oversight"],
    featured: true,
  },
  {
    id: "tm2",
    name: "Chiamaka Eze",
    role: "Head of Design & Product Development",
    image: IMG.teamDesigner,
    bio: "Chiamaka develops furniture concepts, layouts and shop drawings — translating a client's space and brief into pieces the workshop can manufacture precisely.",
    focus: ["Concept design", "Shop drawings", "Material selection"],
    featured: false,
  },
  {
    id: "tm3",
    name: "Emeka Nwankwo",
    role: "Production Manager",
    image: IMG.teamProduction,
    bio: "Emeka runs the factory floor, coordinating cutting, edging, assembly and hardware so each order is built to the agreed specification and schedule.",
    focus: ["Workshop production", "Scheduling", "Build quality"],
    featured: false,
  },
  {
    id: "tm4",
    name: "Blessing Daniel",
    role: "Finishing & Quality Lead",
    image: IMG.teamFinishing,
    bio: "Blessing is responsible for sanding, finishing and the final inspection every piece passes before it leaves the workshop.",
    focus: ["Surface finishing", "Quality inspection", "Packaging"],
    featured: false,
  },
  {
    id: "tm5",
    name: "Ibrahim Suleiman",
    role: "Delivery & Installation Lead",
    image: IMG.teamInstallation,
    bio: "Ibrahim manages dispatch and on-site installation, making sure furniture arrives complete, is fitted correctly and the space is left ready to use.",
    focus: ["Logistics", "On-site installation", "Handover"],
    featured: false,
  },
  {
    id: "tm6",
    name: "Wemi Adesanya",
    role: "Client Relations & Quotations",
    image: IMG.teamClient,
    bio: "Wemi is the first point of contact for enquiries, preparing quotations, answering product questions and keeping clients updated through production.",
    focus: ["Enquiries", "Quotations", "After-sales support"],
    featured: false,
  },
];

export const enquiries: Enquiry[] = [
  { id: "e1", fullName: "Sample Enquiry — A. Bassey", companyName: "[Sample Company]", phone: "[phone pending]", email: "[email pending]", furnitureType: "Workstations", quantity: "24 positions", description: "Sample record showing the enquiry table layout. Requires 24 workstations with storage for an administrative floor.", preferredContact: "Email", source: "Product Enquiry", status: "New", createdAt: "2025-02-18" },
  { id: "e2", fullName: "Sample Enquiry — C. Okoro", companyName: "[Sample Company]", phone: "[phone pending]", email: "[email pending]", furnitureType: "Executive Desks", quantity: "3", description: "Sample record. Three executive desks with credenzas for a management suite.", preferredContact: "Phone", source: "Quote Request", status: "Contacted", createdAt: "2025-02-17" },
  { id: "e3", fullName: "Sample Enquiry — M. Adeyemi", companyName: "[Sample Company]", phone: "[phone pending]", email: "[email pending]", furnitureType: "Reception Desks", quantity: "1", description: "Sample record. Custom reception counter for a new branch office.", preferredContact: "WhatsApp", source: "Custom Furniture", status: "In Progress", createdAt: "2025-02-15" },
  { id: "e4", fullName: "Sample Enquiry — F. Nwosu", companyName: "[Sample Company]", phone: "[phone pending]", email: "[email pending]", furnitureType: "Conference Tables", quantity: "2", description: "Sample record. Two meeting tables seating eight people each.", preferredContact: "Email", source: "Project Enquiry", status: "Completed", createdAt: "2025-02-11" },
  { id: "e5", fullName: "Sample Enquiry — S. Etim", companyName: "[Sample Company]", phone: "[phone pending]", email: "[email pending]", furnitureType: "Office Chairs", quantity: "40", description: "Sample record. Forty ergonomic task chairs for a call-centre floor.", preferredContact: "Phone", source: "WhatsApp Enquiry", status: "Archived", createdAt: "2025-02-02" },
];

export const businessSettings: BusinessSettings = {
  companyName: "LUCOMI ENTERPRISE",
  tagline: "Quality Office Furniture • Better Workspaces",
  logoUrl: "",
  phone: ["234-80-23773065", "234-80-72251045"],
  email: "oninilucky@yahoo.com",
  address: "#17 Ikezam Street, Ozuoba, Port Harcourt, Rivers State, Nigeria.",
  whatsapp: "234-80-23773065",
  businessHours: "",
  social: {
    facebook: "https://www.facebook.com/lucomienterprise",
    instagram: "https://www.instagram.com/lucomienterprise",
    tiktok: "https://www.tiktok.com/@lucomienterprise",
    twitter: "https://x.com/lucomienterprise",
  },
  aboutIntro:
    "LUCOMI ENTERPRISE designs and manufactures functional, durable and stylish office furniture for professional environments — from individual pieces for a single office to complete furniture packages for whole workplaces.",
};
